### ISSUE TITLE
Issues with receiving data from callMain

### ISSUE THREAD

**Issue by phouse512** [sindresorhus/electron-better-ipc#14]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2460%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/electron-better-ipc/issues/14)

Hello, I've run into this issue over the past week that I've been unable to move beyond, and I would appreciate another pair of eyes.

In my renderer, I have 2 separate pieces of code that use `callMain` to get a response back from the main process. One of them returns data just fine, the other returns nothing at all, despite logging showing that the main listener receives it and returns successfully. I even used devtron to see that a message is getting sent to the renderer, but for some reason the listener is not working as expected. 

I wonder if I am just fundamentally misinterpreting the library, or if there is something causing my second call to fail. Any thoughts would be appreciated. Main and rendering code is shown below:

`renderer.js`
```js
// this function works fine
function* checkExistingUser() {
  console.log('checking existing user.');
  const resp = yield ipc.callMain('check-existing-user', 'TESTUSER');
  if (resp.error) {
    console.error('Received error from ipc main');
    return;
  }
  // other behavior
}

// this function doesn't return data from callMain
function* unlockUserCredentials(action) {
  let localUserData = yield select(getLocalData);
  // code makes it here, logging shows up
  try {
    const resp = yield ipc.callMain('unlock-user-credentials', credData);
    console.log(resp); // never shows up in logs
  } catch (error) {
    console.log(error); // never shows up in logs
  }
}
```

My main file:
```js
// this function responds fine, and data is accessible on the client
ipc.answerRenderer('check-existing-user', async data => {
  // working returns
  return {};
});

// this function returns successfully, even with try catch
ipc.answerRenderer('unlock-user-credentials', async data => {
  return {
    message: 'sample data',
  };
});
```

am I doing something wrong by having multiple ipc answer renderers here? Any thoughts or ideas are appreciated. As a note, my renderer code is written for use with `redux-saga`.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($60.00)
### Submitted pull Requests
- [#16 Bugfix #14](https://issuehunt.io/r/sindresorhus/electron-better-ipc/pull/16)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/electron-better-ipc/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by WhiteMinds** [comment]
I had a similar problem.
You can try the downgraded version to solve this problem.

**Comment by phouse512** [comment]
@WhiteMinds which version did you downgrade to? thanks for the help!

**Comment by WhiteMinds** [comment]
> @WhiteMinds你把哪个版本降级为？谢谢您的帮助！

"electron-better-ipc": "^0.2.0"

**Comment by particle4dev** [comment]
Reported
I had a similar problem. My package version is 0.3.0

**Comment by phouse512** [comment]
@particle4dev if you use 0.2.0, does it solve your problem?

**Comment by particle4dev** [comment]
@phouse512 yes, I downgrade to 0.2.0 and it solves my problem. You can try!

**Comment by garrylachman** [comment]
I fix the issue in my fork.
https://github.com/garrylachman/electron-better-ipc

**Comment by burningTyger** [comment]
The issue seems to be still active. I have to use the fork to receive messages in Main.
