### ISSUE TITLE
Cant receive ipc msg after webpack hot reload

### ISSUE THREAD

**Issue by WhiteMinds** [sindresorhus/electron-better-ipc#15]
> main.js
`
ipcMain.answerRenderer(IPCMsg.GetConfig, () => {
  return config.data
})
`

> renderer.js
`
async load () {
      let data = await ipcRenderer.callMain(IPCMsg.GetConfig)
      console.log(data)
}
`

Everything is normal at startup, but after modifying some code to trigger a hot update, ipcRenderer can only send messages, can't receive messages.

In electron-better-ipc/source/renderer.js:6
`const ipc = Object.create(ipcRenderer);`
Modify to
`const ipc = ipcRenderer;`
Fixed this bug

I don't know why

**Comment by WhiteMinds** [comment]
I did more tests and found that it wasn't the hot reload that caused the problem.
The IPC created by Object.create can only receive messages once, direct use of ipcRenderer can normally receive all messages

**Comment by phouse512** [comment]
I was seeing similar issues as described in #14. Doing what WhiteMinds did above and modifying my `source/main.js` and `source/renderer.js` to no longer use `Object.create` fixed it. Any ideas or reasoning?

**Comment by zxc23** [comment]
Have been noticing this myself. Any downside to changing this line?

**Comment by papb** [comment]
Hello @sindresorhus can you please describe the reasoning for using `Object.create` here?

**Comment by mgenware** [comment]
@WhiteMinds I ran into this. Thanks for your workaround, saved me hours of debugging!

**Comment by sindresorhus** [comment]
@papb `Object.create()` is used to create a new object, so we don't add our methods directly to the `electron` IPC API. Doing so would be bad as simply requiring `electron-better-ipc` somewhere in the dependency tree would add these methods for all consumers.

**Comment by sindresorhus** [comment]
This is clearly an issue with hot reloading. I would recommend opening an issue on https://github.com/webpack/webpack instead. `Object.create()` is a commonly-used API. It should be supported for hot-reloading.

**Comment by papb** [comment]
@sindresorhus Thanks for the response. Makes sense. Although when I asked, I was thinking of the following alternative:

```diff
- const ipc = Object.create(ipcMain || {});
+ const ipc = {};
```

And then in the places where you use standard electron IPC APIs:

```diff
- ipc.off(dataChannel, onData);
+ ipcMain.off(dataChannel, onData);
```

But I think I know the answer. You chose to provide a "better" IPC (hence the name of the package!), so you wanted all standard APIs to also exist in your exported object. Am I correct?

**Comment by sindresorhus** [comment]
> You chose to provide a "better" IPC (hence the name of the package!), so you wanted all standard APIs to also exist in your exported object. Am I correct?

Correct
