### ISSUE TITLE
Communicating between two renderer processes

### ISSUE THREAD

**Issue by zxc23** [sindresorhus/electron-better-ipc#17]
What is the recommended solution for communicating between two renderer processes? Should the main process be in the middle to coordinate it?

**Comment by zxc23** [comment]
Well I'm using the main process as the go-between (I've read that there is no way around this) and it looks a bit like this:

`  ipcMain.answerRenderer('get_microphone_device', () => {
    return ipcMain.callRenderer(mainWindow, 'get_microphone_device');
  });`

Closing the issue as this seems to work fine.

**Comment by johanneslumpe** [comment]
You could consider leveraging the [Broadcast Channel API](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API), which will allow you to communicate directly between Chrome windows.

**Comment by aperkaz** [comment]
@johanneslumpe thanks, great advise!
It works like a charm 🙂
