### ISSUE TITLE
Use `any` instead of `unknown`

### ISSUE THREAD

**Issue by dusansimic** [sindresorhus/electron-better-ipc#23]
I'm working on https://github.com/sindresorhus/caprine/issues/848 and I've hit a wall when I wanted to receive data from `answerRendered` function. The problem is passed data is defined in `answerRenderer` with `unknown` type which can't later on be assigned to other values with any other type than `unknown`.

My best idea is to use type `any` instead of `unknown`. Other option is to use `unknown` type on every ipc handling in Caprine which doesn't sound very nice to me.

@BendingBender  I'd love your thoughts on this too since you wrote up TypeScript definitions.

**Comment by sindresorhus** [comment]
You can specify the type when calling the methods, it just defaults to `unknown`. See: https://github.com/sindresorhus/electron-better-ipc/commit/473fa9a89820d9cff16dd154fcafc78e85f481b3

**Comment by dusansimic** [comment]
Yes, but still on `answerRednerer` and `answerMain` functions, `data` parameter in callback function is of type `unknown` even when generic type is specified.

Here is an example
```javascript
ipcMain.answerRenderer<Conversation[]>('conversations', (conversations: Conversation[]) => {
	updateBadge(conversations);
});
```

and this is the error message.

```
source/index.ts:363:58 - error TS2345: Argument of type '(conversations: Conversation[]) => void' is not assignable to parameter of type '(data: unknown, browserWindow: BrowserView) => Conversation[] | PromiseLike<Conversation[]>'.
  Types of parameters 'conversations' and 'data' are incompatible.
    Type 'unknown' is not assignable to type 'Conversation[]'.

363  ipcMain.answerRenderer<Conversation[]>('conversations', (conversations: Conversation[]) => {
```

I want to change the type of data parameter that is being sent to the callback function, not the type of return value from callback function.

The generic type that is being specified for `answer` functions is referring to the type of return value of callback function and type that is being specified for `call` functions is referring to the type of data that is being passed to the listener.

**Comment by sindresorhus** [comment]
I'm not sure why you cannot just do `data as YourType`?

We could maybe make both of them generic, but I'm not really sure the value of that. I'm honestly not even convinced of the value of making the first one generic.

**Comment by dusansimic** [comment]
Well, when I call `callMain` i can specify data type for the data parameter that will be passed to the callback but in `answerRenderer` definition data parameter in callback is always defined as `unknown` (generic type cannot change it) hence the error is thrown.

A two generic types would be useful since then, developer can specify both the type of data that is received and the type of data that is sent back.

**Comment by dusansimic** [comment]
> I'm not sure why you cannot just do `data as YourType`?

Well, it'll look much better if I can specify a type I'm working with instead of using `data as type` whenever I want to use that value.

**Comment by vladimiry** [comment]
@dusansimic you could try https://github.com/vladimiry/electron-rpc-api if you need methods signatures, including the payload type, to be fully typed/predefined.
