### ISSUE TITLE
what's the difference with `invoke handle`  in Electron v7

### ISSUE THREAD

**Issue by Auxxxxlx** [sindresorhus/electron-better-ipc#25]
I am considering whether it is better to switch to new API in electron v7 or not ?

**Comment by Laruxo** [comment]
`ipcRenderer.sendSync()` is syncronous and as written in documentation will block the process until response is received.
> Note: Sending a synchronous message will block the whole renderer process, unless you know what you are doing you should never use it.

I see no benefit of using it instead of this package.

**Comment by Auxxxxlx** [comment]
My mistake, let me explain..

### main --> renderer

###### main process
```javascript
win.webContents.send('main-process-message', false);

```
###### renderer process
```javascript
ipcRenderer.on("main-process-message", (event, arg) => {
        state.isActivated = arg;
      });
```

### renderer --> main
 What I want to talk about is `handle` and `invoke`, which are  new added features in electron v7.0.0: [Release Notes](https://electronjs.org/releases/stable#release-notes-for-v700)


Related article: [Electron’s ‘remote’ module considered harmful](https://medium.com/@nornagon/electrons-remote-module-considered-harmful-70d69500f31)

###### main process
```javascript

ipcMain.handle("windowOperator",async (event, ...args) => {})
```
###### renderer process
```javascript
await ipcRenderer.invoke("renderer-process-message", arguement);
```

**Comment by Laruxo** [comment]
That is a good point, I just discovered this API. I tried using it instead of this module in my current project, seems like it works the same way.
