### ISSUE TITLE
Calling `ipc.callFocusedRenderer` when no windows are focused

### ISSUE THREAD

**Issue by kaatt** [sindresorhus/electron-better-ipc#29]
The following error is thrown when no windows are focused and `ipc.callFocusedRenderer` is called:

```
TypeError: Cannot read property 'id' of null
    at [node_modules]/electron-better-ipc/source/main.js:10:98
    at new Promise (<anonymous>)
    at IpcMainImpl.ipc.callRenderer ([node_modules]/electron-better-ipc/source/main.js:9:54)
    at IpcMainImpl.ipc.callFocusedRenderer ([node_modules]/electron-better-ipc/source/main.js:46:44)
```

Took me a bit of time to debug, should probably help another person googling it. Would be good to handle this and throw a more descriptive error message.

cc #27 @ulken

**Comment by ulken** [comment]
@kaatt Good catch. I'll have a look.

**Comment by ulken** [comment]
@sindresorhus Would you like this to be exclusively handled by `callFocusedRenderer()` or by `callRenderer()` in general?

**Comment by sindresorhus** [comment]
> Handle both cases?

👍

**Comment by ulken** [comment]
Alright, [PR #30](https://github.com/sindresorhus/electron-better-ipc/pull/30) up.
