### ISSUE TITLE
Can't resolve 'fs'

### ISSUE THREAD

**Issue by johannesjo** [sindresorhus/electron-better-ipc#36]
As soon as I use this in my webpack build (via angular cli) for the renderer I get the error above.

```
import { ipcRenderer } from 'electron-better-ipc';
console.log(ipcRenderer);
```
Leads to:
``` 
Module not found: Error: Can't resolve 'fs' in '/home/mememe/www/super-productivity/node_modules/electron'
```

**Comment by sindresorhus** [comment]
That is a problem with Webpack. Use the Webpack support channels. It works find when run directly without Webpack.

**Comment by johannesjo** [comment]
Setting 
```
  node: {
    fs: 'empty'
  }
```
in the webpack config which seems to be the standard workaround for this doesn't work for me as I am now with the error `fs.existsSync is not a function`. I am using electron 9.1.1.

**Comment by serg06** [comment]
@johannesjo Did you ever figure it out?

**Comment by serg06** [comment]
Update, I got it working [here](https://github.com/electron/electron/issues/9920#issuecomment-901429728).
